[VCI]
products = VCI,VLI

[VCS]
products = VCS,UVC-VLS

[VCM]
products = VCM,UVC-VLM

[RECOVERY]
products = UVC-VL-GM2-1CAM-UnknownBoot,UVC-VL-FPD3-1CAM-UnknownBoot,VC-UnknownBoot

[TEVS]
products = TEVS,VLS-GM2

[TEVM]
products = TEVM,VLM-GM2
