[VCI]
products = VCI,VLI

[VCS]
products = VCS,UVC-VLS,UVC-VLS-GM2,UVC-VL-GM2-4CAM

[VCM]
products = VCM,UVC-VLM,UVC-VLM-GM2

[TEVS]
products = TEVS,VLS-GM2

[TEVM]
products = TEVM,VLM-GM2